"""
Autonomous Research OS (Ver 3.0)
マルチエージェント型特許自動生成パイプライン
"""

import os
import json
import time
import feedparser
import google.generativeai as genai
from github import Github
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPO")

genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-1.5-pro")


def call_llm(prompt: str, retries: int = 3) -> str:
    for attempt in range(retries):
        try:
            response = model.generate_content(prompt)
            return response.text
        except Exception as e:
            if attempt < retries - 1:
                wait = 2 ** attempt
                print(f"  [LLM Error] {e} — {wait}s後にリトライ...")
                time.sleep(wait)
            else:
                raise


# ─── Phase 1: RAG ────────────────────────────────────────────────────────────

def fetch_arxiv_papers(query: str = "LLM polymer design", max_results: int = 5) -> str:
    print(f"[Phase 1] arXivから論文取得: '{query}'")
    url = (
        f"https://export.arxiv.org/api/query"
        f"?search_query=all:{query.replace(' ', '+')}"
        f"&start=0&max_results={max_results}"
        f"&sortBy=submittedDate&sortOrder=descending"
    )
    feed = feedparser.parse(url)
    summaries = []
    for entry in feed.entries:
        summaries.append(
            f"Title: {entry.title}\n"
            f"Authors: {', '.join(a.name for a in entry.authors)}\n"
            f"Summary: {entry.summary[:400]}..."
        )
    return "\n\n---\n\n".join(summaries) if summaries else "論文が取得できませんでした。"


def fetch_failure_log() -> str:
    print("[Phase 1] GitHubからfailure_log.md を取得...")
    try:
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(GITHUB_REPO)
        contents = repo.get_contents("failure_log.md")
        return contents.decoded_content.decode("utf-8")
    except Exception as e:
        print(f"  [Warning] failure_log.md が見つかりません ({e})。空のログを使用します。")
        return "（失敗ログなし — 初回実行）"


# ─── Phase 2: 推論（マルチエージェント） ────────────────────────────────────

def agent1_mad_scientist(papers: str, failure_log: str) -> str:
    print("[Phase 2] Agent 1: 狂気の科学者 — 新メカニズム提案中...")
    prompt = f"""あなたは「狂気の科学者」エージェントです。
制約を無視して、革命的かつ斬新な科学的メカニズムを提案してください。

## 最新論文
{papers}

## 過去の失敗ログ
{failure_log}

## 指示
- 上記の論文と失敗ログを踏まえ、全く新しいアプローチや材料設計メカニズムを提案してください。
- 既存の常識を打ち破るアイデアを優先してください。
- 提案は具体的かつ技術的に記述してください（500〜800字程度）。
"""
    return call_llm(prompt)


def agent2_patent_attorney(mechanism: str) -> str:
    print("[Phase 2] Agent 2: 特許弁理士 — 新規性と請求項を作成中...")
    prompt = f"""あなたは「特許弁理士」エージェントです。

## 提案されたメカニズム
{mechanism}

## 指示
以下の形式で特許案を作成してください。

### 【発明の名称】
（簡潔なタイトル）

### 【技術分野】
（技術領域の説明）

### 【従来技術との差異（新規性）】
（先行技術との具体的な違い）

### 【独立請求項】
請求項1: ...

### 【従属請求項】
請求項2〜5: ...

### 【発明の効果】
（期待される技術的効果）
"""
    return call_llm(prompt)


def agent3_mi_engineer(patent_draft: str) -> str:
    print("[Phase 2] Agent 3: MIエンジニア — Dry検証アプローチを提案中...")
    prompt = f"""あなたは「マテリアルズインフォマティクス（MI）エンジニア」エージェントです。

## 特許案
{patent_draft}

## 指示
上記の特許案をDry検証（計算・シミュレーション）するための具体的なPythonコードや手法を提案してください。

- 使用するライブラリ・ツール（例: RDKit, ASE, DFT, 機械学習モデル等）
- 検証ステップの概要
- 簡単なPythonコードスニペット（実行可能なもの）
- 期待される検証結果の指標
"""
    return call_llm(prompt)


# ─── Phase 3: 評価 ───────────────────────────────────────────────────────────

def agent4_cso_evaluate(mechanism: str, patent_draft: str, validation: str) -> dict:
    print("[Phase 3] Agent 4: CSO — 評価中...")
    prompt = f"""あなたは「最高科学責任者（CSO）」エージェントです。
以下の研究提案を厳格に評価し、JSON形式で結果を出力してください。

## 提案メカニズム
{mechanism}

## 特許案
{patent_draft}

## 検証アプローチ
{validation}

## 評価基準
- 新規性（0〜30点）: 既存技術との差別化
- 実現可能性（0〜30点）: 技術的な実現可能性
- 市場インパクト（0〜20点）: 産業への貢献度
- 検証アプローチの妥当性（0〜20点）: Dry検証の具体性

## 出力形式（必ずこのJSONのみを出力）
{{"score": 85, "reason": "評価理由を200字程度で", "final_summary": "提案の要約を100字程度で"}}
"""
    raw = call_llm(prompt)

    # JSONを抽出（余分なテキストが含まれる場合に対応）
    start = raw.find("{")
    end = raw.rfind("}") + 1
    if start == -1 or end == 0:
        raise ValueError(f"JSONが見つかりません。LLM出力:\n{raw}")
    return json.loads(raw[start:end])


# ─── Phase 4: 出力 ───────────────────────────────────────────────────────────

def format_markdown(mechanism: str, patent_draft: str, validation: str, evaluation: dict) -> str:
    return f"""# 🧬 Autonomous Research OS — 特許提案レポート

## スコア: {evaluation['score']} / 100

### 評価コメント
{evaluation['reason']}

---

## Agent 1: 新メカニズム提案（狂気の科学者）

{mechanism}

---

## Agent 2: 特許案（特許弁理士）

{patent_draft}

---

## Agent 3: Dry検証アプローチ（MIエンジニア）

{validation}

---

## Agent 4: 総合評価（CSO）

- **スコア**: {evaluation['score']} 点
- **理由**: {evaluation['reason']}
- **最終要約**: {evaluation['final_summary']}

---
*Generated by Autonomous Research OS v3.0*
"""


def post_github_issue(title: str, body: str) -> str:
    print("[Phase 4] GitHubにIssueを起票中...")
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(GITHUB_REPO)
    issue = repo.create_issue(title=title, body=body, labels=[])
    return issue.html_url


# ─── メインパイプライン ───────────────────────────────────────────────────────

def run_pipeline():
    print("=" * 60)
    print("  Autonomous Research OS v3.0 起動")
    print("=" * 60)

    # Phase 1: RAG
    papers = fetch_arxiv_papers("LLM polymer design")
    failure_log = fetch_failure_log()

    # Phase 2: 推論
    mechanism = agent1_mad_scientist(papers, failure_log)
    patent_draft = agent2_patent_attorney(mechanism)
    validation = agent3_mi_engineer(patent_draft)

    # Phase 3: 評価
    evaluation = agent4_cso_evaluate(mechanism, patent_draft, validation)

    score = evaluation["score"]
    print(f"\n[結果] スコア: {score} / 100")
    print(f"[結果] 理由: {evaluation['reason']}")

    # Phase 4: 出力
    if score >= 80:
        print(f"\n✅ スコア {score} — GitHub Issueとして起票します。")
        body = format_markdown(mechanism, patent_draft, validation, evaluation)
        title = f"[Patent Proposal] {evaluation['final_summary'][:60]}"
        url = post_github_issue(title, body)
        print(f"\n🎉 Issue起票完了: {url}")
    else:
        print(f"\n❌ スコア {score} — ボツ。再実行または手動調整を検討してください。")
        print(f"理由: {evaluation['reason']}")

    print("\n" + "=" * 60)
    print("  パイプライン完了")
    print("=" * 60)


if __name__ == "__main__":
    run_pipeline()
